# Generated by Django 6.0.6 on 2026-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
